### ISSUE TITLE
Thread 'main' panicked when using class_g()

### ISSUE THREAD

**Issue by iamcodernitesh** [pierrechevalier83/workstyle#13] opened 2021-11-09 08:53 UTC
Issue : class_g() functionality does not work .
Error message : 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Wanted { expected: "an equals", found: "an identifier" }, line: Some(11), col: 10, at: Some(321), message: "", key: [] } }', src/config.rs:105:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Config.toml : 
```
"class_g("kitty")" = ""
# "class_g("firefox")" = ""
"github" = ""
"rust" = ""
"google" = ""
"private browsing" = ""
"firefox" = ""
"chrome" = ""
"file manager" = ""
"libreoffice calc" = ""
"libreoffice writer" = ""
"libreoffice" = ""
"nvim" = ""
"gthumb" = ""
"menu" = ""
"calculator" = ""
"transmission" = ""
"videostream" = ""
"mpv" = ""
"music" = ""
"disk usage" = ""
".pdf" = ""
[other]
"fallback_icon" = ""
```
Installed using : AUR (https://aur.archlinux.org/packages/workstyle-git)

**Comment by pierrechevalier83** [comment] 2021-11-10 09:20
This functionality that is requested in #6 hasn't been implemented yet. Closing as a duplicate of #6 for consolidation.

**Closed by pierrechevalier83** 2021-11-10 09:20 UTC
