### ISSUE TITLE
Workstyle lock persists after terminating sway session

### ISSUE THREAD

**Issue by uberyb** [pierrechevalier83/workstyle#41] opened 2022-04-23 22:39 UTC
If I terminate my sway session and reload into it, I can no longer start workstyle with error "Failed to acquire the lock". I find I have to manually remove run/user/1000/workstyle.lock in order to be able to run workstyle again.

Is there any sort of clean exit behavior that can be added to workstyle so I don't have to do this step manually each time?

**Comment by MaxVerevkin** [comment] 2022-04-24 07:43
How do you exit sway? Which OS do you use?

**Comment by uberyb** [comment] 2022-04-26 19:08
I am using manjaro. I exit sway usually by mod+shift+e which by default runs `exec swaynag`.

**Comment by LDAP** [comment] 2023-03-26 11:20
This can be reproduced as follows:
- Open a terminal (alacritty)
- Execute `workstyle`
- Close the terminal
- Reopen the terminal
- Execute `workstyle` → breaks

What does work is to first exit `workstyle` with Ctrl+C and then closing the terminal.

**Comment by pierrechevalier83** [comment] 2023-04-15 11:17
I can't reproduce this on sway however I try (I tried `exec workstyle` and `exec systemctl --restart workstyle`).

I'm guessing that @uberyb is using a way to exec that spawns a terminal that spawns `workstyle`, so the repro from @LDAP does cover this.

If that is the case, https://github.com/pierrechevalier83/workstyle/pull/57 should address it. I can repro with the steps from https://github.com/pierrechevalier83/workstyle/issues/41#issuecomment-1484065818 and handling SIGHUP does solve the situation in that case.

**Comment by pierrechevalier83** [comment] 2023-04-15 11:19
I've merged #57. I will close the issue now.

If anyone sees this issue on latest main, please re-open.

**Closed by pierrechevalier83** 2023-04-15 11:19 UTC

**Comment by wjdp** [comment] 2024-04-26 18:27
I'm getting this issue on what I think is the latest available version. Installed using `cargo install --force workstyle` and getting `workstyle v0.8.2`.

I run workstyle via `exec_always --no-startup-id ~/.cargo/bin/workstyle` in sway config

If sway crashes then the lock persists and does not start again without removing. I didn't know where it would be so thankful for @uberyb for documenting.
