### ISSUE TITLE
100% CPU Usage on Window Manager Reload

### ISSUE THREAD

**Issue by iamcodernitesh** [pierrechevalier83/workstyle#15] opened 2021-12-16 04:37 UTC
When reloading the window manager workstyle consumes 100% cpu usage. and when reloaded again and again more instances are created each consuming 100% cpu usage.
![image](https://user-images.githubusercontent.com/73643989/146309012-3a7a78bc-908f-4a94-b973-96e3af475133.png)

**Comment by pierrechevalier83** [comment] 2021-12-16 08:30
Thanks for the report, @iamcodernitesh.
I have also observed this behaviour if your config starts workstyle as a background task and nothing kills it, more and more instances will be launched and they will end up competing for access to the window manager through the IPC protocol.

One workaround is to killall workstyle after reloading the window manager, or using this in your sway config to do it autmatically:
```
exec killall workstyle
exec --no-startup-id workstyle &> /tmp/workstyle.log
```

A better fix might be to split workstyle into 2 processes: one  launcher process and one daemon process. The launcher process checks if the daemon is alive, and if not, starts a new one. The daemon does the work.

**Comment by pierrechevalier83** [comment] 2021-12-17 23:02
It should be fixed with this https://github.com/pierrechevalier83/workstyle/commit/b8eef266632b72995807eb71923c102038f5f994

If you've installed `workstyle` from the aur, or cargo, please install the latest version (`main`'s `HEAD`, a.k.a 0.6.1) and let me know if it behaves correctly now.

**Comment by iamcodernitesh** [comment] 2021-12-24 14:02
Still the same issue. Last log file reads this
```
Error: "Couldn't acquire lock: /tmp/workstyle.lock already exists"
```

**Comment by pierrechevalier83** [comment] 2022-01-08 20:03
@iamcodernitesh , I've refactored the code to use async/await. I've tested various scenarios with i3 and sway, including leaving the window manager and coming back. I also added some logging.

Could you try to install the latest version (0.7.0) from the `aur` or `cargo install` and let me know if this issue is resolved for you now?
If you still see abnormal behaviour, could you set `RUST_LOG=debug` and share the logs with me?

**Comment by pierrechevalier83** [comment] 2022-02-13 14:48
Closing this issue because my recent changes fixed it as far as I can reproduce. Please re-open if you hit this again.

**Closed by pierrechevalier83** 2022-02-13 14:48 UTC
